name: Compile WifiX Deauther

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "SimpleCLI"
          arduino-cli lib install "ArduinoJson"@5.13.5

      - name: Prepare Folder Structure
        run: |
          # Trik supaya Arduino CLI gak error:
          # Buat folder bernama 'WifiXv1.5' dan pindahkan semua file ke sana
          mkdir WifiXv1.5
          cp -r * WifiXv1.5/ || true
          # Hapus folder build lama jika ada
          rm -rf build

      - name: Compile Firmware
        run: |
          # Compile dari dalam folder yang baru dibuat
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          ./WifiXv1.5/WifiXv1.5.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: WifiX-Deauther-Bin
          path: ./build/*.bin
