name: GMpro87-Final-Unlocked

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "SimpleCLI"
          arduino-cli lib install "ArduinoJson"@5.13.5
          arduino-cli lib install "Adafruit NeoPixel"

      - name: Fix Folder Structure & Rebrand
        run: |
          # 1. Bikin folder yang namanya sama dengan file .ino
          mkdir -p WifiXv1.5
          
          # 2. Pindahin semua file ke folder baru tersebut agar terbaca
          # Pakai find supaya nggak mindahin folder 'WifiXv1.5' ke dalem dirinya sendiri
          find . -maxdepth 1 -not -name "WifiXv1.5" -not -name "." -not -name ".git" -not -name ".github" -exec cp -r {} WifiXv1.5/ \;

          # 3. Suntik library NeoPixel langsung ke folder project
          cp /home/runner/Arduino/libraries/Adafruit_NeoPixel/*.h WifiXv1.5/
          cp /home/runner/Arduino/libraries/Adafruit_NeoPixel/*.cpp WifiXv1.5/
          
          # Fix include agar pakai file lokal (tanda kutip)
          sed -i 's/#include <Adafruit_NeoPixel.h>/#include "Adafruit_NeoPixel.h"/g' WifiXv1.5/led.cpp

          # 4. Bypass Aktivasi & Rebranding
          sed -i 's/if(EEPROM.read(400) == 1)/if(true)/g' WifiXv1.5/WifiXv1.5.ino
          sed -i 's/return loop();//g' WifiXv1.5/WifiXv1.5.ino
          
          # Ganti WifiX 1.5 & asp29 jadi GMpro87
          find WifiXv1.5 -maxdepth 1 -type f \( -name "*.ino" -o -name "*.h" -o -name "*.cpp" \) -exec sed -i 's/WifiX 1.5/dev : GMpro87/g' {} +
          find WifiXv1.5 -maxdepth 1 -type f \( -name "*.ino" -o -name "*.h" -o -name "*.cpp" \) -exec sed -i 's/asp29/dev : GMpro87/g' {} +

      - name: Compile Firmware
        run: |
          # Compile folder WifiXv1.5 yang sudah rapi
          arduino-cli compile --fqbn deauther:esp8266:d1_mini:eesz=4M3M \
          --libraries /home/runner/Arduino/libraries \
          ./WifiXv1.5 --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro87-Final-Bin
          path: ./build/*.bin
