name: Compile WifiX Deauther WemosD1

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "SimpleCLI"
          arduino-cli lib install "ArduinoJson"@5.13.5

      - name: Prepare Folder Structure
        run: |
          # 1. Buat folder kerja sesuai standar
          mkdir -p WifiXv1.5
          # Copy semua file kecuali folder itu sendiri untuk menghindari loop
          find . -maxdepth 1 -not -name 'WifiXv1.5' -not -name '.' -exec cp -r {} WifiXv1.5/ \;

      - name: Compile Firmware
        run: |
          # Pakai d1_mini tanpa tambahan suntik pin manual karena sudah ada di core
          arduino-cli compile --fqbn deauther:esp8266:d1_mini:eesz=4M3M \
          ./WifiXv1.5/WifiXv1.5.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: WifiX-WemosD1-Binary
          path: ./build/*.bin
