name: GMpro87-Final-Unlocked

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "SimpleCLI"
          arduino-cli lib install "ArduinoJson"@5.13.5
          arduino-cli lib install "Adafruit NeoPixel"

      - name: Ultimate Rebranding GMpro87
        run: |
          mkdir -p WifiXv1.5
          # Copy semua file ke folder project baru
          find . -maxdepth 1 -not -name 'WifiXv1.5' -not -name '.' -exec cp -r {} WifiXv1.5/ \;

          # 1. BYPASS AKTIVASI (Force True)
          # Mengganti pengecekan EEPROM agar selalu dianggap sudah aktif
          sed -i 's/if(EEPROM.read(400) == 1)/if(true)/g' WifiXv1.5/WifiXv1.5.ino
          sed -i 's/return loop();//g' WifiXv1.5/WifiXv1.5.ino

          # 2. FULL REBRAND (WifiX & asp29 -> dev: GMpro87)
          find WifiXv1.5 -type f \( -name "*.ino" -o -name "*.h" -o -name "*.cpp" \) -exec sed -i 's/WifiX 1.5/dev : GMpro87/g' {} +
          find WifiXv1.5 -type f \( -name "*.ino" -o -name "*.h" -o -name "*.cpp" \) -exec sed -i 's/asp29/dev : GMpro87/g' {} +
          find WifiXv1.5/web_interface -name "*.h" -exec sed -i 's/Deauther/GMpro87/g' {} +

          # 3. HAPUS TEKS AKTIVASI & INTRO
          find WifiXv1.5/web_interface -name "*.h" -exec sed -i 's/Device Activation://g' {} +
          find WifiXv1.5/web_interface -name "*.h" -exec sed -i 's/Click >HERE< to open activation page//g' {} +
          sed -i 's/displayUI.drawIntro/#define NO_INTRO/g' WifiXv1.5/WifiXv1.5.ino

          # 4. WIFI & OLED CONFIG
          # Pastikan SSID dan Password sesuai keinginan lo
          sed -i 's/#define AP_SSID "#WifiX.1.5#"/#define AP_SSID "Vivo1904"/g' WifiXv1.5/A_config.h
          sed -i 's/#define AP_PASSWD "deauther"/#define AP_PASSWD "Sangkur87"/g' WifiXv1.5/A_config.h
          sed -i '/#elif defined(NODEMCU)/,/#elif/ s/SH1106_I2C/SSD1306_I2C/g' WifiXv1.5/A_config.h

      - name: Compile Firmware
        run: |
          # Gunakan konfigurasi D1 Mini dengan 4MB Flash
          arduino-cli compile --fqbn deauther:esp8266:d1_mini:eesz=4M3M \
          ./WifiXv1.5/WifiXv1.5.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro87-Final-Bin
          path: ./build/*.bin
